# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
env:
  GCS_BUCKET: ${{secrets.GCS_BUCKET}}
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gcp-sync:
    name: GCP Sync
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCS_SA_KEY }}'

      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v0

      - run: |-
          gsutil rsync -d -r images gs://$GCS_BUCKET
          
        
      
