# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
env:
  GCS_BUCKET: ${{secrets.GCS_BUCKET}}
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gcp-sync:
    name: GCP Sync
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCS_SA_KEY }}'

      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v0

      - name: sync bucket
        run: |-
          gsutil rsync -r images gs://$GCS_BUCKET

      - name: Grant all users public access
        run: |-
          gsutil acl ch -u AllUsers:R gs://$GCS_BUCKET
          
        
      
